# This file was generated by the {rix} R package v0.17.2 on 2025-10-16
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("rmarkdown",
#  > "blogdown",
#  > "jsonlite",
#  > "knitr",
#  > "rix",
#  > "purrr",
#  > "reactable",
#  > "dplyr"),
#  > system_pkgs = c("hugo",
#  > "jq"),
#  > py_conf = list(py_version = "3.12",
#  > py_pkgs = c("requests")),
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      blogdown
      dplyr
      jsonlite
      knitr
      purrr
      reactable
      rix
      rmarkdown;
  };
   
  pyconf = builtins.attrValues {
    inherit (pkgs.python312Packages) 
      pip
      ipykernel
      requests;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      hugo
      jq
      nix
      python312
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python312}/bin/python";

    buildInputs = [ rpkgs pyconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
