# Test all participating sites on awesome-blogdown.com

name: Site tests

# Controls when the action will run, in this case a schedule.
on:
  schedule:
  - cron: "0 4 * * 1,4" # At 04:00 on Monday and Thursday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
  
      - name: Build development environment
        run: |
          nix-build

      - name: Assemble integrated site JSON file
        run: nix-shell --run "bash tools/build-json.sh data/json data/all.json"

      - name: Run site testing script
        run: nix-shell --run "python tools/ab200.py"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest site data snapshot: ${timestamp}" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

